### ISSUE TITLE
Fix database issues

### ISSUE THREAD

**Issue by firepol** [firepol/ccxt-websockets-db-updater#3]
Websockets order books are flooding the database. The problem is that SQLAlchemy doens't seem thread safe as I read, or not supporting async.

E.g. bitfinex "takes over" and order books from other exchanges are not saved anymore. But I see no error messages in the logs. So I think the WS connection works, it's just the part of savign to the DB that seems to be skipped for those.

Try a different postgres driver or wrapper.

E.g.:

- https://aiopg.readthedocs.io/en/stable/sa.html
- https://github.com/MagicStack/asyncpg
- https://github.com/CanopyTax/asyncpgsa

Then get rid of the hack (that doesn't even work properly) introduced in this commit: 7e2dca1e761a98d7d5111d0087ac08c8d5d3b409

Implications: queries may be rewritten, but the goal is still to keep using SQLAlchemy ORM, to allow using different databases.

**Comment by firepol** [comment]
Botmaster recommended:

> What if you store in a unique list or dictionary for each connection and then have a separate thread to parse through and pick out what you want to retain, sort/order and commit to POSTGRES?
> Essentially acting as a buffer with the parsing and committing done every x seconds

Basically:
- instead of (actual problematic solution) processing every order book (update or insert to DB): add the values to a dictionary
- have a separate parallel task process the dictionary (and save to DB) every x ms, e.g. every 80ms to begin, then try to go down to 30ms, make sure no concurrent writes occur

**Comment by simonarabian** [comment]
Am "botmaster". Can confirm our interaction above via Telegram!
