### ISSUE TITLE
python3 ./ob_tester.py -e cex -s ETH/BTC = websocket error

### ISSUE THREAD

**Issue by ng2dev** [firepol/ccxt-websockets-db-updater#5]
(myenv) ➜  ccxt-websockets-db-updater git:(master) ✗ python3 ./ob_tester.py -e cex -s ETH/BTC --verbose 

Could not find ./data/exchange_api_keys.json
------------------------------>
wss://ws.cex.io/ws/
ParseResult(scheme='wss', netloc='ws.cex.io', path='/ws/', params='', query='', fragment='')
cex, 2019-03-09 13:39:10.371241, [<FrameSummary file ./ob_tester.py, line 45 in <module>>, <FrameSummary file ./ob_tester.py, line 34 in main>, <FrameSummary file /usr/lib/python3.6/asyncio/base_events.py, line 427 in run_forever>, <FrameSummary file /usr/lib/python3.6/asyncio/base_events.py, line 1440 in _run_once>, <FrameSummary file /usr/lib/python3.6/asyncio/events.py, line 145 in _run>, <FrameSummary file /home/oem/python/ccxt-websockets-db-updater/ob_updater.py, line 103 in websocket_error>]

**Comment by firepol** [comment]
Hi @ng2dev as you see in the error message: `Could not find ./data/exchange_api_keys.json`

Cex.io needs authentication for the websockets... so you must insert uid, apiKey and secret as explained in the readme. In the configuration chapter I wrote:

Some exchanges (like cex.io) need to be authenticated via api key / secret. Add your api keys in the `data/exchange_api_keys.json` file (you find a template in the samples folder).

See `samples/exchange_api_keys.json`

Hope this helps, if it does please close the issue, cheers

**Comment by ng2dev** [comment]
Thank you
